// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: proto/server.proto

package rocket_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Md5    string `protobuf:"bytes,1,opt,name=md5,proto3" json:"md5,omitempty"`
	Sha1   string `protobuf:"bytes,2,opt,name=sha1,proto3" json:"sha1,omitempty"`
	Sha256 string `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
}

func (x *HashCode) Reset() {
	*x = HashCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashCode) ProtoMessage() {}

func (x *HashCode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashCode.ProtoReflect.Descriptor instead.
func (*HashCode) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{0}
}

func (x *HashCode) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *HashCode) GetSha1() string {
	if x != nil {
		return x.Sha1
	}
	return ""
}

func (x *HashCode) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type EntryMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string    `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Hash     *HashCode `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Size     int64     `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	URI      string    `protobuf:"bytes,4,opt,name=URI,proto3" json:"URI,omitempty"`
}

func (x *EntryMessage) Reset() {
	*x = EntryMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryMessage) ProtoMessage() {}

func (x *EntryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryMessage.ProtoReflect.Descriptor instead.
func (*EntryMessage) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{1}
}

func (x *EntryMessage) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *EntryMessage) GetHash() *HashCode {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *EntryMessage) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *EntryMessage) GetURI() string {
	if x != nil {
		return x.URI
	}
	return ""
}

type AccessCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *AccessCode) Reset() {
	*x = AccessCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessCode) ProtoMessage() {}

func (x *AccessCode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessCode.ProtoReflect.Descriptor instead.
func (*AccessCode) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{2}
}

func (x *AccessCode) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_proto_server_proto protoreflect.FileDescriptor

var file_proto_server_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x22, 0x48, 0x0a, 0x08, 0x48, 0x61, 0x73, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x64,
	0x35, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x68, 0x61, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x68, 0x61, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x22, 0x7d, 0x0a,
	0x0c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52,
	0x49, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x49, 0x22, 0x22, 0x0a, 0x0a,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x32, 0xa4, 0x01, 0x0a, 0x0f, 0x41, 0x69, 0x72, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x12, 0x4c, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x2e, 0x72, 0x6f, 0x63,
	0x6b, 0x65, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x19, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x43, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12,
	0x19, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x1b, 0x2e, 0x72, 0x6f, 0x63,
	0x6b, 0x65, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x72, 0x6f, 0x63,
	0x6b, 0x65, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_server_proto_rawDescOnce sync.Once
	file_proto_server_proto_rawDescData = file_proto_server_proto_rawDesc
)

func file_proto_server_proto_rawDescGZIP() []byte {
	file_proto_server_proto_rawDescOnce.Do(func() {
		file_proto_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_server_proto_rawDescData)
	})
	return file_proto_server_proto_rawDescData
}

var file_proto_server_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_server_proto_goTypes = []interface{}{
	(*HashCode)(nil),     // 0: rocket_server.HashCode
	(*EntryMessage)(nil), // 1: rocket_server.EntryMessage
	(*AccessCode)(nil),   // 2: rocket_server.AccessCode
}
var file_proto_server_proto_depIdxs = []int32{
	0, // 0: rocket_server.EntryMessage.hash:type_name -> rocket_server.HashCode
	1, // 1: rocket_server.AirRocketServer.GenerateAccessCode:input_type -> rocket_server.EntryMessage
	2, // 2: rocket_server.AirRocketServer.GetDetail:input_type -> rocket_server.AccessCode
	2, // 3: rocket_server.AirRocketServer.GenerateAccessCode:output_type -> rocket_server.AccessCode
	1, // 4: rocket_server.AirRocketServer.GetDetail:output_type -> rocket_server.EntryMessage
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_server_proto_init() }
func file_proto_server_proto_init() {
	if File_proto_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntryMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_server_proto_goTypes,
		DependencyIndexes: file_proto_server_proto_depIdxs,
		MessageInfos:      file_proto_server_proto_msgTypes,
	}.Build()
	File_proto_server_proto = out.File
	file_proto_server_proto_rawDesc = nil
	file_proto_server_proto_goTypes = nil
	file_proto_server_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AirRocketServerClient is the client API for AirRocketServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AirRocketServerClient interface {
	GenerateAccessCode(ctx context.Context, in *EntryMessage, opts ...grpc.CallOption) (*AccessCode, error)
	GetDetail(ctx context.Context, in *AccessCode, opts ...grpc.CallOption) (*EntryMessage, error)
}

type airRocketServerClient struct {
	cc grpc.ClientConnInterface
}

func NewAirRocketServerClient(cc grpc.ClientConnInterface) AirRocketServerClient {
	return &airRocketServerClient{cc}
}

func (c *airRocketServerClient) GenerateAccessCode(ctx context.Context, in *EntryMessage, opts ...grpc.CallOption) (*AccessCode, error) {
	out := new(AccessCode)
	err := c.cc.Invoke(ctx, "/rocket_server.AirRocketServer/GenerateAccessCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airRocketServerClient) GetDetail(ctx context.Context, in *AccessCode, opts ...grpc.CallOption) (*EntryMessage, error) {
	out := new(EntryMessage)
	err := c.cc.Invoke(ctx, "/rocket_server.AirRocketServer/GetDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AirRocketServerServer is the server API for AirRocketServer service.
type AirRocketServerServer interface {
	GenerateAccessCode(context.Context, *EntryMessage) (*AccessCode, error)
	GetDetail(context.Context, *AccessCode) (*EntryMessage, error)
}

// UnimplementedAirRocketServerServer can be embedded to have forward compatible implementations.
type UnimplementedAirRocketServerServer struct {
}

func (*UnimplementedAirRocketServerServer) GenerateAccessCode(context.Context, *EntryMessage) (*AccessCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAccessCode not implemented")
}
func (*UnimplementedAirRocketServerServer) GetDetail(context.Context, *AccessCode) (*EntryMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetail not implemented")
}

func RegisterAirRocketServerServer(s *grpc.Server, srv AirRocketServerServer) {
	s.RegisterService(&_AirRocketServer_serviceDesc, srv)
}

func _AirRocketServer_GenerateAccessCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntryMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirRocketServerServer).GenerateAccessCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rocket_server.AirRocketServer/GenerateAccessCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirRocketServerServer).GenerateAccessCode(ctx, req.(*EntryMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirRocketServer_GetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirRocketServerServer).GetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rocket_server.AirRocketServer/GetDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirRocketServerServer).GetDetail(ctx, req.(*AccessCode))
	}
	return interceptor(ctx, in, info, handler)
}

var _AirRocketServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rocket_server.AirRocketServer",
	HandlerType: (*AirRocketServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateAccessCode",
			Handler:    _AirRocketServer_GenerateAccessCode_Handler,
		},
		{
			MethodName: "GetDetail",
			Handler:    _AirRocketServer_GetDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/server.proto",
}
